In [1]:
import pandas as pd

df = pd.read_csv('orders.csv', parse_dates=['time'])
df

                  time symbol       price side
0  2027-06-01 08:02:00   MSFT  264.125209  bid
1  2027-06-01 08:02:17   MSFT  265.501745  ask
2  2027-06-01 08:02:34    IBM  145.990889  bid
3  2027-06-01 08:02:51   ORCL   78.809339  ask
4  2027-06-01 08:03:08   ORCL   78.621716  ask
5  2027-06-01 08:03:25    IBM  146.394603  bid
6  2027-06-01 08:03:42   MSFT  264.541463  bid
7  2027-06-01 08:03:59   MSFT  265.920656  ask
8  2027-06-01 08:04:16   ORCL   77.832466  bid
9  2027-06-01 08:04:33   MSFT  265.690728  ask
10 2027-06-01 08:04:50   ORCL   78.983019  ask
11 2027-06-01 08:05:07    IBM  147.435275  ask
12 2027-06-01 08:05:24   MSFT  265.485622  ask
13 2027-06-01 08:05:41   MSFT  265.194916  ask
14 2027-06-01 08:05:58   MSFT  264.661838  bid
15 2027-06-01 08:06:15   MSFT  265.684405  ask
16 2027-06-01 08:06:32    NaN  265.443295  ask
17 2027-06-01 08:06:49   ORCL   79.272016  ask
18 2027-06-01 08:07:06    IBM  146.316067  bid
19 2027-06-01 08:07:23   ORCL   77.975912  bid

In [2]:
def is_valid_row(row):
    if row['time'] < pd.Timestamp('1900'):
        return False

    if pd.isnull(row['symbol']) or row['symbol'].strip() == '':
        return False

    if row['price'] <= 0:
        return False

    return True


ok_df = df[df.apply(is_valid_row, axis=1)]

In [3]:
num_bad = len(df) - len(ok_df)
percent_bad = num_bad/len(df) * 100
print(f'{percent_bad:.2f}% bad rows')
if num_bad > 0:
    bad_rows = df[~df.index.isin(ok_df.index)]
    print('bad rows:')
    print(bad_rows)

5.00% bad rows
bad rows:
                  time symbol       price side
16 2027-06-01 08:06:32    NaN  265.443295  ask